# Generated by Django 4.2.7 on 2024-06-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=100)),
                ('titulo_obtenido', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'educacion',
                'verbose_name_plural': 'lugares_educacion',
            },
        ),
    ]
