# Generated by Django 4.2.7 on 2024-06-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0002_educacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Educacion',
            new_name='Institucion_educativa',
        ),
        migrations.AlterModelOptions(
            name='institucion_educativa',
            options={'verbose_name': 'institucion_educativa', 'verbose_name_plural': 'instituciones_educativas'},
        ),
        migrations.RenameField(
            model_name='institucion_educativa',
            old_name='institucion',
            new_name='nombre',
        ),
    ]
