# Generated by Django 4.2.7 on 2024-06-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0003_rename_educacion_institucion_educativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('periodo_tiempo', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'experiencia_laboral',
                'verbose_name_plural': 'experiencias_laborales',
            },
        ),
        migrations.CreateModel(
            name='Referencia_familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'verbose_name': 'referencia_familiar',
                'verbose_name_plural': 'referencias_familiares',
            },
        ),
        migrations.CreateModel(
            name='Referencia_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'verbose_name': 'referencia_laboral',
                'verbose_name_plural': 'referencias_laborales',
            },
        ),
        migrations.CreateModel(
            name='Referencia_personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'verbose_name': 'referencia_personal',
                'verbose_name_plural': 'referencias_personales',
            },
        ),
    ]
