# Generated by Django 4.2.7 on 2024-06-25 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0004_experiencia_laboral_referencia_familiar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia_familiar',
            name='telefono',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000000000)]),
        ),
    ]
