# Generated by Django 4.2.7 on 2024-06-25 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0005_alter_referencia_familiar_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia_laboral',
            name='telefono',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000000000)]),
        ),
        migrations.AlterField(
            model_name='referencia_personal',
            name='telefono',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000000000)]),
        ),
    ]
