# Generated by Django 4.2.7 on 2024-06-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0006_alter_referencia_laboral_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia_familiar',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='referencia_laboral',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='referencia_personal',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
