# Generated by Django 4.2.7 on 2024-07-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0008_alter_referencia_familiar_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.ManyToManyField(to='CVApp.tecnologia'),
        ),
    ]
