# Generated by Django 4.2.7 on 2024-07-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0009_tecnologia_proyecto_tecnologias'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
