# Generated by Django 4.2.9 on 2025-09-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0010_proyecto_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referencia_personal',
            new_name='Referencia',
        ),
        migrations.DeleteModel(
            name='Referencia_familiar',
        ),
        migrations.DeleteModel(
            name='Referencia_laboral',
        ),
        migrations.AlterModelOptions(
            name='referencia',
            options={'verbose_name': 'referencia', 'verbose_name_plural': 'referencias'},
        ),
    ]
