# Generated by Django 4.2.9 on 2025-09-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0011_rename_referencia_personal_referencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencia',
            options={'ordering': ['orden'], 'verbose_name': 'referencia', 'verbose_name_plural': 'referencias'},
        ),
        migrations.AddField(
            model_name='referencia',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
