# Generated by Django 4.2.9 on 2025-09-18 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0012_alter_referencia_options_referencia_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencia',
            options={'ordering': ('orden',), 'verbose_name': 'referencia', 'verbose_name_plural': 'referencias'},
        ),
    ]
